# Generated by Django 2.1.5 on 2019-01-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('text', models.CharField(max_length=2048)),
                ('field', models.CharField(choices=[('FTB', 'Football'), ('BSK', 'Basketball'), ('OTH', 'Other')], default='OTH', max_length=3)),
            ],
        ),
    ]
