# Generated by Django 2.1.5 on 2019-01-19 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.UUIDField(auto_created=True, db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
